[target.aarch64-linux-android]
ar = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"

[target.armv7-linux-androideabi]
ar = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi26-clang.cmd"

[target.x86_64-linux-android]
ar = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android26-clang.cmd"

# Note: Ensure API level (26) matches your minSdk in build.gradle.kts
